---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}"
  annotations:
    prometheus.io/port: "9100" 
    prometheus.io/scrape: "true" 
spec:
  selector:
    app: "{{ .Chart.Name }}"
  ports:
  - name: http
    port: 8080
    protocol: TCP
  - name: metrics
    port: 9100
    protocol: TCP
{{ if (eq .Values.werf.env "prod") }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Chart.Name }}-ru"
  annotations:
    prometheus.io/port: "9100" 
    prometheus.io/scrape: "true" 
spec:
  selector:
    app: "{{ .Chart.Name }}-ru"
  ports:
  - name: http
    port: 8080
    protocol: TCP
  - name: metrics
    port: 9100
    protocol: TCP
{{ end }}